# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"h\n\x0fRegisterRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\x12\x10\n\x08password\x18\x05 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1d\n\x0cTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"R\n\x15\x43hangePasswordRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x14\n\x0cold_password\x18\x02 \x01(\t\x12\x14\n\x0cnew_password\x18\x03 \x01(\t\"%\n\x14ResetPasswordRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"P\n\x0c\x41uthResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05token\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t\"C\n\x12ValidationResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\":\n\x16\x43hangePasswordResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"O\n\x15ResetPasswordResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0cnew_password\x18\x03 \x01(\t2\xd5\x02\n\x0b\x41uthService\x12\x37\n\x08Register\x12\x15.auth.RegisterRequest\x1a\x12.auth.AuthResponse\"\x00\x12\x31\n\x05Login\x12\x12.auth.LoginRequest\x1a\x12.auth.AuthResponse\"\x00\x12?\n\rValidateToken\x12\x12.auth.TokenRequest\x1a\x18.auth.ValidationResponse\"\x00\x12M\n\x0e\x43hangePassword\x12\x1b.auth.ChangePasswordRequest\x1a\x1c.auth.ChangePasswordResponse\"\x00\x12J\n\rResetPassword\x12\x1a.auth.ResetPasswordRequest\x1a\x1b.auth.ResetPasswordResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REGISTERREQUEST']._serialized_start=20
  _globals['_REGISTERREQUEST']._serialized_end=124
  _globals['_LOGINREQUEST']._serialized_start=126
  _globals['_LOGINREQUEST']._serialized_end=173
  _globals['_TOKENREQUEST']._serialized_start=175
  _globals['_TOKENREQUEST']._serialized_end=204
  _globals['_CHANGEPASSWORDREQUEST']._serialized_start=206
  _globals['_CHANGEPASSWORDREQUEST']._serialized_end=288
  _globals['_RESETPASSWORDREQUEST']._serialized_start=290
  _globals['_RESETPASSWORDREQUEST']._serialized_end=327
  _globals['_AUTHRESPONSE']._serialized_start=329
  _globals['_AUTHRESPONSE']._serialized_end=409
  _globals['_VALIDATIONRESPONSE']._serialized_start=411
  _globals['_VALIDATIONRESPONSE']._serialized_end=478
  _globals['_CHANGEPASSWORDRESPONSE']._serialized_start=480
  _globals['_CHANGEPASSWORDRESPONSE']._serialized_end=538
  _globals['_RESETPASSWORDRESPONSE']._serialized_start=540
  _globals['_RESETPASSWORDRESPONSE']._serialized_end=619
  _globals['_AUTHSERVICE']._serialized_start=622
  _globals['_AUTHSERVICE']._serialized_end=963
# @@protoc_insertion_point(module_scope)
